### ISSUE TITLE
Market maker agent locks all his money in margin account and reward accounts then it cannot use it.

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega-market-sim#540]
Hello. We are running an incentive on the fairground. Let's say We have the following party which is a `market-maker` for the incentive market: `36b7fd126f0521299d6d489eed78705404ce1868485d9b8123c39f725dcfa6af`

The agent config is the following:

```toml
    [scenario.btcusd_incentive.market_maker_args]
        market_kappa = 0.3
        market_order_arrival_rate = 150
        order_kappa = 0.15
        order_size = 1
        order_levels = 25
        order_spacing = 1
        order_clipping = 10000
        inventory_lower_boundary = -3
        inventory_upper_boundary = 3
        fee_amount = 0.0001
        commitment_amount = 7000000
        initial_mint = 8000000
```

The agent accounts looks like below:

```graphql
query{
  party(id:"36b7fd126f0521299d6d489eed78705404ce1868485d9b8123c39f725dcfa6af") {
    accountsConnection{
      edges{
        node{
          balance,
          asset{symbol},
          type,
          market{id},
        }
      }
    }
  }
}

```

Response:

```
{
  "data": {
    "party": {
      "accountsConnection": {
        "edges": [
          {
            "node": {
              "balance": "0",
              "asset": {
                "symbol": "I-USDT"
              },
              "type": "ACCOUNT_TYPE_LP_LIQUIDITY_FEES",
              "market": {
                "id": "e97144288e3a98f5275e093260861d1f848f2a032990339b0d290f6e8aa43b6e"
              }
            }
          },
          {
            "node": {
              "balance": "0",
              "asset": {
                "symbol": "I-USDT"
              },
              "type": "ACCOUNT_TYPE_GENERAL",
              "market": null
            }
          },
          {
            "node": {
              "balance": "20485637384632",
              "asset": {
                "symbol": "I-USDT"
              },
              "type": "ACCOUNT_TYPE_MARGIN",
              "market": {
                "id": "e97144288e3a98f5275e093260861d1f848f2a032990339b0d290f6e8aa43b6e"
              }
            }
          },
          {
            "node": {
              "balance": "24130714146",
              "asset": {
                "symbol": "I-USDT"
              },
              "type": "ACCOUNT_TYPE_VESTING_REWARDS",
              "market": null
            }
          },
          {
            "node": {
              "balance": "2231524383",
              "asset": {
                "symbol": "I-USDT"
              },
              "type": "ACCOUNT_TYPE_VESTED_REWARDS",
              "market": null
            }
          },
          {
            "node": {
              "balance": "0",
              "asset": {
                "symbol": "I-USDT"
              },
              "type": "ACCOUNT_TYPE_BOND",
              "market": {
                "id": "e97144288e3a98f5275e093260861d1f848f2a032990339b0d290f6e8aa43b6e"
              }
            }
          }
        ]
      }
    }
  }
}
```

It says the party has over 20 million of `USD-I` but see the screen below:

We want to submit 7 millions of the liquidity as per config however the market has all his money locker in the wrong accounts.

<img width="1439" alt="image" src="https://github.com/vegaprotocol/vega-market-sim/assets/1239637/0108bcdc-5005-4257-9e78-e4463f1ca581">

Could We fix the bot, so he can use his own money, please?: )
